export const profileTypes = {
  PROFILE_INFORMATION: "PROFILE_INFORMATION",

  // TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  // ADD_ITEM: "ADD_ITEM",
  // REMOVE_ITEM: "REMOVE_ITEM",
  // DECREMENT_ITEM: "DECREMENT_ITEM",
};
