export const profileTypes = {
  ADD_CONGRATULATIONS: "ADD_CONGRATULATIONS",

  // TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  // ADD_ITEM: "ADD_ITEM",
  // REMOVE_ITEM: "REMOVE_ITEM",
  // DECREMENT_ITEM: "DECREMENT_ITEM",
};
